---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - lenshood.github.io.lenshood.github.io
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lenshood.github.io.lenshood.github.io
  resources:
  - networks/finalizers
  verbs:
  - update
- apiGroups:
  - lenshood.github.io.lenshood.github.io
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
